name: CI - Pruebas Automatizadas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Correr pruebas unitarias
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar dependencias de pruebas
        run: pip install pytest pytest-cov httpx

      - name: Correr pruebas con cobertura
        run: pytest tests/ -v --cov=. --cov-report=term-missing --cov-report=xml:coverage.xml --cov-config=.coveragerc

      - name: Guardar reporte de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura
          path: coverage.xml
